### ISSUE TITLE
Bug with Sugar.js

### ISSUE THREAD

**Issue by ghamha1n** [mlegenhausen/node-ogone-directlink#7]
i use sails.js on node.js

the library work fine but when i did' it crash all server.

give me this error
!!!!!
```
server   |  TypeError: undefined is not a function
server   |     at Array.every (native)
server   |     at Array.<anonymous> (/Users/hamzah/Desktop/giftshop/server/node_modules/ogone-directlink/node_modules/sugar/release/sugar-full.development.js:180:23)
server   |     at Object.module.exports.parseCriteria (/Users/hamzah/Desktop/giftshop/server/node_modules/sails-generate-ember-blueprints/templates/basic/api/blueprints/_util/actionUtil.js:269:28)
server   |     at findRecords (/Users/hamzah/Desktop/giftshop/server/node_modules/sails-generate-ember-blueprints/templates/basic/api/blueprints/find.js:54:24)
server   |     at routeTargetFnWrapper (/Users/hamzah/.npm-packages/lib/node_modules/sails/lib/router/bind.js:179:5)
server   |     at callbacks (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
server   |     at param (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
server   |     at pass (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
server   |     at nextRoute (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
server   |     at callbacks (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
server   |     at /Users/hamzah/.npm-packages/lib/node_modules/sails/lib/router/bind.js:239:18
server   |     at callbacks (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
server   |     at param (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
server   |     at pass (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
server   |     at nextRoute (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
server   |     at callbacks (/Users/hamzah/.npm-packages/lib/node_modules/sails/node_modules/express/lib/router/index.js:167:11) [TypeError: undefined is not a function]
```

**Comment by mlegenhausen** [comment]
The problem will be sugarjs which monkey patches native JavaScript objects.

Cause this library is not under active development anymore you can try to find out what is the problem and provide a pull request.
